# Generated by Django 5.0.6 on 2024-07-17 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sasa', '0002_alter_customuser_county_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodysystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('admin', 'Admin'), ('nurse', 'Nurse'), ('accountant', 'Accountant')], default='patient', max_length=40),
        ),
        migrations.CreateModel(
            name='Systemdiscomfort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discomfort_name', models.CharField(max_length=254)),
                ('body_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasa.bodysystem')),
            ],
        ),
        migrations.CreateModel(
            name='Patientdiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(default='null', max_length=254)),
                ('body_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasa.bodysystem')),
                ('system_discomfort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasa.systemdiscomfort')),
            ],
        ),
    ]
