# Generated by Django 5.0.6 on 2024-07-17 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sasa', '0003_bodysystem_alter_customuser_role_systemdiscomfort_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_name', models.CharField(max_length=254)),
                ('body_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasa.bodysystem')),
            ],
        ),
        migrations.AddField(
            model_name='systemdiscomfort',
            name='symptoms',
            field=models.ManyToManyField(blank=True, to='sasa.symptom'),
        ),
    ]
