# Generated by Django 5.0.6 on 2024-07-18 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sasa', '0004_symptom_systemdiscomfort_symptoms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdiagnosis',
            name='body_system',
        ),
        migrations.RemoveField(
            model_name='systemdiscomfort',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='patientdiagnosis',
            name='first_name',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
