# Generated by Django 5.0.6 on 2024-07-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sasa', '0005_remove_patientdiagnosis_body_system_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdiagnosis',
            old_name='first_name',
            new_name='patient',
        ),
    ]
