# Generated by Django 5.0.6 on 2024-07-29 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sasa', '0006_rename_first_name_patientdiagnosis_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityservice',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='facilityservice',
            name='user_permissions',
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_date', models.DateTimeField()),
                ('appeal_status', models.CharField(default='pending', max_length=254)),
                ('payment_status', models.CharField(default='null', max_length=254)),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasa.facility')),
                ('groups', models.ManyToManyField(blank=True, help_text='user groups', related_name='custom_user_groups', to='auth.group', verbose_name='groups')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='user permissions', related_name='custom_user_permissions', related_query_name='user permissions', to='auth.permission', verbose_name='permissions')),
            ],
        ),
    ]
